const CHANGE_TYPE_MENU="CHANGE_TYPE_MENU";
const CHANGE_TYPE_MENU_SUB_KITCHEN="CHANGE_TYPE_MENU_SUB_KITCHEN";
const CHANGE_TYPE_MENU_SUB_BAR="CHANGE_TYPE_MENU_SUB_BAR";
const CHANGE_ACCOUNT="CHANGE_ACCOUNT";
const CHANGE_LOADING_APP="CHANGE_LOADING_APP";

export {CHANGE_TYPE_MENU, CHANGE_ACCOUNT, CHANGE_LOADING_APP, CHANGE_TYPE_MENU_SUB_KITCHEN, CHANGE_TYPE_MENU_SUB_BAR};