export const GET_BARS = "GET_BARS"
export const GET_BARS_SUCCESS = "GET_BARS_SUCCESS"
export const GET_BARS_FAIL = "GET_BARS_FAIL"

export const POST_BARS = "POST_BARS"
export const POST_BARS_SUCCESS = "POST_BARS_SUCCESS"
export const POST_BARS_FAIL = "POST_BARS_FAIL"

export const DELETE_BARS = "DELETE_BARS"
export const DELETE_BARS_SUCCESS = "DELETE_BARS_SUCCESS"
export const DELETE_BARS_FAIL = "DELETE_BARS_FAIL"


export const UPDATE_BARS = "UPDATE_BARS"
export const UPDATE_BARS_SUCCESS = "UPDATE_BARS_SUCCESS"
export const UPDATE_BARS_FAIL = "UPDATE_BARS_FAIL"

