export const POST_BOOKING =  "POST_BOOKING";
export const POST_BOOKING_SUCCESS =  "POST_BOOKING_SUCCESS";
export const POST_BOOKING_FAIL =  "POST_BOOKING_FAIL";

export const GET_BOOKING =  "GET_BOOKING";
export const GET_BOOKING_SUCCESS =  "GET_BOOKING_SUCCESS";
export const GET_BOOKING_FAIL =  "GET_BOOKING_FAIL";

export const DELETE_BOOKING =  "DELETE_BOOKING";
export const DELETE_BOOKING_SUCCESS =  "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAIL =  "DELETE_BOOKING_FAIL";

export const UPDATE_BOOKING =  "UPDATE_BOOKING";
export const UPDATE_BOOKING_SUCCESS =  "UPDATE_BOOKING_SUCCESS";
export const UPDATE_BOOKING_FAIL =  "UPDATE_BOOKING_FAIL";

export const SEARCH_BOOKING =  "SEARCH_BOOKING";
export const SEARCH_BOOKING_SUCCESS =  "SEARCH_BOOKING_SUCCESS";
export const SEARCH_BOOKING_FAIL =  "SEARCH_BOOKING_FAIL";









