export const POST_FEEDBACK =  "POST_FEEDBACK";
export const POST_FEEDBACK_SUCCESS =  "POST_FEEDBACK_SUCCESS";
export const POST_FEEDBACK_FAIL =  "POST_FEEDBACK_FAIL";

export const GET_FEEDBACK =  "GET_FEEDBACK";
export const GET_FEEDBACK_SUCCESS =  "GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_FAIL =  "GET_FEEDBACK_FAIL";










