export const POST_CHICKEN = "POST_CHICKEN"
export const POST_CHICKEN_SUCCESS = "POST_CHICKEN_SUCCESS"
export const POST_CHICKEN_FAIL = "POST_CHICKEN_FAIL"

export const GET_CHICKEN = "GET_CHICKEN"
export const GET_CHICKEN_SUCCESS = "GET_CHICKEN_SUCCESS"
export const GET_CHICKEN_FAIL = "GET_CHICKEN_FAIL"

export const DELETE_CHICKEN = "DELETE_CHICKEN"
export const DELETE_CHICKEN_SUCCESS = "DELETE_CHICKEN_SUCCESS"
export const DELETE_CHICKEN_FAIL = "DELETE_CHICKEN_FAIL"

export const EDIT_CHICKEN = "EDIT_CHICKEN"
export const EDIT_CHICKEN_SUCCESS = "EDIT_CHICKEN_SUCCESS"
export const EDIT_CHICKEN_FAIL = "EDIT_CHICKEN_FAIL"






