export const GET_KIETCHEN_DAY = "GET_KIETCHEN_DAY"
export const GET_KIETCHEN_DAY_SUCCESS = "GET_KIETCHEN_DAY_SUCCESS"
export const GET_KIETCHEN_DAY_FAIL = "GET_KIETCHEN_DAY_FAIL"

export const POST_KITCHEN_DAY = "POST_KITCHEN_DAY"
export const POST_KITCHEN_DAY_SUCCESS = "POST_KITCHEN_DAY_SUCCESS"
export const POST_KITCHEN_DAY_FAIL = "POST_KITCHEN_DAY_FAIL"

export const DELETE_KITCHEN_DAY = "DELETE_KITCHEN_DAY"
export const DELETE_KITCHEN_DAY_SUCCESS = "DELETE_KITCHEN_DAY_SUCCESS"
export const DELETE_KITCHEN_DAY_FAIL = "DELETE_KITCHEN_DAY_FAIL"

