export const POST_SPENDING = "POST_SPENDING"
export const POST_SPENDING_SUCCESS = "POST_SPENDING_SUCCESS"
export const POST_SPENDING_FAIL = "POST_SPENDING_FAIL"

export const GET_SPENDING = "GET_SPENDING"
export const GET_SPENDING_SUCCESS = "GET_SPENDING_SUCCESS"
export const GET_SPENDING_FAIL = "GET_SPENDING_FAIL"

export const DELETE_SPENDING = "DELETE_SPENDING"
export const DELETE_SPENDING_SUCCESS = "DELETE_SPENDING_SUCCESS"
export const DELETE_SPENDING_FAIL = "DELETE_SPENDING_FAIL"





