export const POST_STAFF = "POST_STAFF"
export const POST_STAFF_SUCCESS = "POST_STAFF_SUCCESS" 
export const POST_STAFF_FAIL = "POST_STAFF_FAIL" 

export const GET_STAFF = "GET_STAFF"
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS"
export const GET_STAFF_FAIL = "GET_STAFF_FAIL"

export const DELETE_STAFF = "DELETE_STAFF"
export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS"
export const DELETE_STAFF_FAIL = "DELETE_STAFF_FAIL"

export const UPDATE_STAFF = "UPDATE_STAFF"
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS"
export const UPDATE_STAFF_FAIL = "UPDATE_STAFF_FAIL"








