const COLOR = '#01a3a4';
const COLOR_MENU_ADMIN = '#fff'
const BACKGROUND_MENU_ADMIN = '#01a3a4'
const MENU_TAB_CLIENT = {
    HOME_PAGE: "HOME_PAGE",
    INTRODUCE: "INTRODUCE",
    BOOKING: "BOOKING",
    OFFER: "OFFER",
    FEEDBACK: "FEEDBACK",
    CONTACT: "CONTACT"
}

const MENU_TAB_ADMIN = {
    MENU: "MENU",
    AREA: "AREA",
    BAR: "BAR",
    BOOK: "BOOK",
    KITCHEN: "KITCHEN",
    SPENDING: "SPENDING",
    STAFF: "STAFF",
    TURNOVER: "TURNOVER"
}


const ONE_DAY = 86399000

const PATTETN ={
    EMAIL: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/
}

export {COLOR, COLOR_MENU_ADMIN , BACKGROUND_MENU_ADMIN ,MENU_TAB_CLIENT, ONE_DAY, PATTETN, MENU_TAB_ADMIN}