const COLOR = '#01a3a4';
const MENU_TAB_CLIENT = {
    HOME_PAGE: "HOME_PAGE",
    INTRODUCE: "INTRODUCE",
    BOOKING: "BOOKING",
    OFFER: "OFFER",
    FEEDBACK: "FEEDBACK",
    CONTACT: "CONTACT"
}
const ONE_DAY = 86399000

export {COLOR,MENU_TAB_CLIENT, ONE_DAY}